/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

import javax.swing.JOptionPane;

/**
 *
 * @author Aby
 */
public class Latihan02 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan02
     */
    public Latihan02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panjangBlk = new javax.swing.JTextField();
        lebarBlk = new javax.swing.JTextField();
        tinggiBlk = new javax.swing.JTextField();
        btbalok = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sisiKbs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btkubus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jari2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btbola = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("MASUKKAN PANJANG");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 60, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("MASUKKAN LEBAR");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 130, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("MASUKKAN TINGGI");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 200, 190, 30);

        panjangBlk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(panjangBlk);
        panjangBlk.setBounds(270, 50, 460, 50);

        lebarBlk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(lebarBlk);
        lebarBlk.setBounds(270, 120, 460, 50);

        tinggiBlk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(tinggiBlk);
        tinggiBlk.setBounds(270, 190, 460, 50);

        btbalok.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btbalok.setText("Hitung");
        btbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbalokActionPerformed(evt);
            }
        });
        jPanel2.add(btbalok);
        btbalok.setBounds(270, 270, 160, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("cm");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(740, 200, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("cm");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(740, 60, 50, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("cm");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(740, 130, 50, 30);

        jTabbedPane1.addTab("Balok", jPanel2);

        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("MASUKKAN NILAI SISI");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 31, 287, 42);

        sisiKbs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(sisiKbs);
        sisiKbs.setBounds(40, 80, 290, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("cm");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(340, 90, 27, 22);

        btkubus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btkubus.setText("Volume");
        btkubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkubusActionPerformed(evt);
            }
        });
        jPanel3.add(btkubus);
        btkubus.setBounds(40, 140, 140, 40);

        jTabbedPane1.addTab("Kubus", jPanel3);

        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("MASUKKAN NILAI JARI-JARI");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(36, 32, 270, 36);

        jari2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(jari2);
        jari2.setBounds(40, 80, 280, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("cm");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(330, 90, 27, 22);

        btbola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btbola.setText("Volume");
        btbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbolaActionPerformed(evt);
            }
        });
        jPanel4.add(btbola);
        btbola.setBounds(40, 140, 150, 50);

        jTabbedPane1.addTab("Bola", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 60, 1040, 580);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PROGRAM PENCARI VOLUME BANGUN RUANG");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 20, 570, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(15, 16, 1060, 670);

        setBounds(0, 0, 1108, 756);
    }// </editor-fold>//GEN-END:initComponents

    private void btkubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(sisiKbs.getText());
        int hasil = sisi*sisi*sisi;
        
        try{
            JOptionPane.showMessageDialog(null,"Volume kubus adalah : "+
                    hasil+"cm^3","Hasil",JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error : "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btkubusActionPerformed

    private void btbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbalokActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(panjangBlk.getText());
        lebar = Integer.parseInt(lebarBlk.getText());
        tinggi = Integer.parseInt(tinggiBlk.getText());
        int hasil = panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil+"cm^3","Hasil",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error : "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btbalokActionPerformed

    private void btbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(jari2.getText());
        float hasil1 = (float)(4/3*3.14*jari*jari*jari);
        try{
            JOptionPane.showMessageDialog(null,"Volume Bola adalah : "+hasil1+"cm^3","Hasil",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error : "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btbolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbalok;
    private javax.swing.JButton btbola;
    private javax.swing.JButton btkubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jari2;
    private javax.swing.JTextField lebarBlk;
    private javax.swing.JTextField panjangBlk;
    private javax.swing.JTextField sisiKbs;
    private javax.swing.JTextField tinggiBlk;
    // End of variables declaration//GEN-END:variables
}
